-- Migration #58: Phase 4.1 — political_subject_stance + event_type expansion
--
-- First non-Fed atomic stance table. Per the brief: don't generalize
-- speaker_word_stance, build per-domain siblings. This is the politics
-- atomic table — one row per speaker × subject × statement.
--
-- Stance axis is escalatory_deescalatory (vs Fed's hawkish_dovish).
-- Schema is per-statement, not per-word: a speaker can have many
-- statements on the same subject; the composer rolls them up into one
-- mention_event per (speaker, subject) at the latest statement date.

create table if not exists political_subject_stance (
  id uuid primary key default gen_random_uuid(),
  speaker text not null,
  subject text not null,
  -- Statement reference: a unique slug naming this specific statement
  -- (truth-social-2026-04-07-civilization, press-conf-2024-09-01-iran).
  -- Combined with (speaker, subject) for de-dup on re-ingest.
  statement_id text,
  statement_date date,
  statement_source_url text,
  -- Optional ≤15-word verbatim quote — feeds the blurb prompt directly
  -- so the LLM has quote material on hand without re-fetching the source.
  statement_quote text,
  stance_value text not null check (stance_value in (
    'escalatory', 'deescalatory', 'ambiguous', 'insufficient_signal'
  )),
  stance_confidence text check (stance_confidence in ('high','medium','low')),
  blurb text,
  rationale text,
  created_at timestamptz not null default now(),
  judged_at timestamptz,
  unique (speaker, subject, statement_id)
);

create index if not exists idx_political_subject_stance_speaker_subject
  on political_subject_stance(speaker, subject);

create index if not exists idx_political_subject_stance_subject
  on political_subject_stance(subject)
  where stance_value != 'insufficient_signal';

create index if not exists idx_political_subject_stance_judgable
  on political_subject_stance(stance_value)
  where stance_value != 'insufficient_signal';

-- Expand mention_events.event_type CHECK to allow non-Fed event shapes.
-- Constraint name auto-generated by Postgres as <table>_<column>_check
-- when defined inline. DROP IF EXISTS handles re-runs cleanly.
alter table mention_events drop constraint if exists mention_events_event_type_check;
alter table mention_events add constraint mention_events_event_type_check
  check (event_type in (
    'fomc_presser','speech','rally','testimony','presser','hearing','other',
    'statement','social_post','press_release','op_ed','interview','rally_remarks'
  ));

-- RLS — public read on the political stance table, writes via service-role
alter table political_subject_stance enable row level security;
create policy "political subject stance is public read"
  on political_subject_stance for select using (true);
